### ISSUE TITLE
creating of the spark user fails, with an existing kerberos/ldap managed user that has different home or shell attributes

### ISSUE THREAD

**Issue by lhoss** [azavea/ansible-spark#12]
I provided a fix in our repos (based on latest 'develop' branch, see https://github.com/azavea/ansible-spark/pull/10 ) : https://github.com/teralytics/ansible-spark/pull/7

**Comment by hectcastro** [comment]
What is the error you are seeing? Also, this seems like it could be an issue with the underlying Ansible `user` module.

**Comment by lhoss** [comment]
When deploying on a server with a spark user managed by ldap/kerberos, found by 'getent' :  $ /usr/bin/getent passwd spark

> spark:*:4351:4351:Spark Jobs:/home/spark:/bin/bash

I the error:

> TASK [../../ansible-spark : Create service account for Spark] ******************
> task path: /Users/lhoss/IdeaProjects/ansible-spark/tasks/main.yml:2
> fatal: [ffs.zh.teralytics.net]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"append": false, "comment": null, "createhome": true, "expires": null, "force": false, "generate_ssh_key": null, "group": null, "groups": "users,data", "home": "/var/lib/spark", "login_class": null, "move_home": false, "name": "spark", "non_unique": false, "password": null, "remove": false, "shell": "/bin/false", "skeleton": null, "ssh_key_bits": "2048", "ssh_key_comment": "ansible-generated on...", "ssh_key_file": null, "ssh_key_passphrase": null, "ssh_key_type": "rsa", "state": "present", "system": true, "uid": null, "update_password": "always"}, "module_name": "user"}, "msg": "usermod: user 'spark' does not exist in /etc/passwd\n", "name": "spark", "rc": 6}

I did not find any existing ansible (user module) issue, but I also expect that ansible(user) could handle such a case properly. 

UPDATE:  The issue is actually that some user attributes are different (in my case 'home' and 'shell') and when ansible tries to modify these (in /etc/passwd !) , it fails.

When I ran a test deploy with these 2 differing attributes removed, then ansible handled the existing kerberos user correctly!

I guess an alternative fix for us: is to be able to set the spark user's shell attribute (instead of the default '/bin/false')

**Comment by hectcastro** [comment]
Ah, good catch. A PR to make the Spark user's shell a variable would definitely be accepted.

**Comment by hectcastro** [comment]
This was resolved by #16, correct?

**Comment by lhoss** [comment]
yes
